import { Router } from "express";
import authRoutes from "./authRoutes.js";
import horarioRoutes from "./horarioRoutes.js";
import canchasRoutes from "./canchaRoutes.js";
import reservaRoutes from "./reservaRoutes.js";
import aprobacionRoutes from "./aprobacionRoutes.js";
import jugadorRoutes from "./jugadorRoutes.js";
import grupoJugadorRoutes from "./GrupoJugadorRoutes.js";
import sesionRoutes from "./sesionRoutes.js";
import asistenciaRoutes from "./asistenciaRoutes.js";
import sesionTokenRoutes from "./sesionTokenRoutes.js";
import evaluacionRoutes from "./evaluacionRoutes.js";
import lesionRoutes from "./lesionRoutes.js";
import estadisticaRoutes from "./estadisticaRoutes.js";
import alineacionRoutes from "./alineacionRoutes.js";
import campeonatoRoutes from "./campeonatoRoutes.js";
import equipoRoutes from "./equipoRoutes.js";
import partidoRoutes from "./partidoRoutes.js";
import estadisticaCampeonatoRoutes from "./estadisticaCampeonatoRoutes.js";
import entrenamientoSesionRoutes from "./entrenamientoSesionRoutes.js";
const router = Router();

router.use("/auth", authRoutes);
router.use("/horario", horarioRoutes);
router.use("/canchas", canchasRoutes);
router.use("/reservas", reservaRoutes);
router.use("/aprobacion", aprobacionRoutes);
router.use("/jugadores", jugadorRoutes);
router.use("/grupos", grupoJugadorRoutes);
router.use("/sesion", sesionRoutes);
router.use("/asistencia", asistenciaRoutes);
router.use("/sesionToken", sesionTokenRoutes);
router.use("/evaluaciones", evaluacionRoutes);
router.use("/lesiones", lesionRoutes);
router.use("/estadisticas", estadisticaRoutes);
router.use("/alineaciones", alineacionRoutes);
router.use("/campeonato", campeonatoRoutes);
router.use("/equipo", equipoRoutes);
router.use("/partido", partidoRoutes);
router.use("/estadisticaCampeonato", estadisticaCampeonatoRoutes);
router.use("/entrenamientos", entrenamientoSesionRoutes);
export default router;